sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11
addons:
  postgresql: "9.4"
  firefox: "60.3.0esr"
cache:
  directories:
    - $HOME/.m2
services:
  - xvfb

install:
  - pushd `pwd`
  - cd $HOME/build
  - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=master; fi
  - git clone --depth=1 --branch=$GFW_BRANCH https://github.com/terasolunaorg/terasoluna-gfw.git terasolunaorg/terasoluna-gfw
  - cd terasolunaorg/terasoluna-gfw
  - sh ./mvn-build-all.sh -B install -P default -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
  - popd

before_script:
  - psql -c 'create database tourreserve;' -U postgres
  - export CARGO_DAEMON_WEBAPP_VERSION=1.6.2
  - mvn -B dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script: 
  - mvn -B xml:check-format
  - mvn -B xml:check-format -f terasoluna-tourreservation-initdb/pom.xml
  - mvn -B xml:check-format -f terasoluna-tourreservation-selenium/pom.xml
  - mvn -B formatter:validate
  - mvn -B -U sql:execute -f terasoluna-tourreservation-initdb/pom.xml -Ddb.password=
  - mvn -B -U install
  - mvn -B -U cargo:daemon-start -f terasoluna-tourreservation-web/pom.xml
  - mvn -B -U test -f terasoluna-tourreservation-selenium/pom.xml
