sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
  firefox: "latest-esr"
env:
  global:
  - PGPORT=5433
cache:
  directories:
    - $HOME/.m2
services:
  - xvfb

install:
  - pushd `pwd`
  - cd $HOME/build
  - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=master; fi
  - git clone --depth=1 --branch=$GFW_BRANCH https://github.com/terasolunaorg/terasoluna-gfw.git terasolunaorg/terasoluna-gfw
  - cd terasolunaorg/terasoluna-gfw
  - sh ./mvn-build-all.sh -B install -P default -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
  - export CARGO_DAEMON_WEBAPP_VERSION=`mvn -B -f terasoluna-gfw-parent/pom.xml help:evaluate -Dexpression=cargo-maven2-plugin.version | grep -v '^\['`
  - popd

before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/11/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - psql -c 'create database tourreserve;' -U postgres
  - mvn -B dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script: 
  - mvn -B xml:check-format
  - mvn -B xml:check-format -f terasoluna-tourreservation-initdb/pom.xml
  - mvn -B xml:check-format -f terasoluna-tourreservation-selenium/pom.xml
  - mvn -B formatter:validate
  - mvn -B license:check
  - mvn -B -U sql:execute -f terasoluna-tourreservation-initdb/pom.xml -Ddb.url=jdbc:postgresql://127.0.0.1:${PGPORT}/tourreserve -Ddb.password=
  - sed -i -e "s/localhost/localhost:${PGPORT}/" *env/src/main/resources/META-INF/*/*infra.properties
  - mvn -B -U install
  - mvn -B -U cargo:daemon-start -f terasoluna-tourreservation-web/pom.xml
  - mvn -B -U test -f terasoluna-tourreservation-selenium/pom.xml
