sudo: required
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
  firefox: "38.8.0esr"
cache:
  directories:
    - $HOME/.m2

install:
  - pushd `pwd`
  - cd $HOME/build
  - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=1.0.x; fi
  - git clone --depth=1 --branch=$GFW_BRANCH https://github.com/terasolunaorg/terasoluna-gfw.git terasolunaorg/terasoluna-gfw
  - cd terasolunaorg/terasoluna-gfw
  - sh ./mvn-build-all.sh -B install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
  - export CARGO_DAEMON_WEBAPP_VERSION=`mvn -B -f terasoluna-gfw-parent/pom.xml help:evaluate -Dexpression=cargo-maven2-plugin.version | grep -v '^\['`
  - popd

before_script:
  - psql -c 'create database tourreserve;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export MAVEN_DEPENDENCY_PLUGIN_VERSION=2.8
  - mvn -B org.apache.maven.plugins:maven-dependency-plugin:${MAVEN_DEPENDENCY_PLUGIN_VERSION}:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script:
  - mvn -B xml:check-format
  - mvn -B xml:check-format -f terasoluna-tourreservation-initdb/pom.xml
  - mvn -B xml:check-format -f terasoluna-tourreservation-selenium/pom.xml
  - mvn -B formatter:validate
  - mvn -B -U sql:execute -f terasoluna-tourreservation-initdb/pom.xml -Ddb.password=
  - mvn -B -U install
  - mvn -B -U cargo:daemon-start -f terasoluna-tourreservation-web/pom.xml
  - mvn -B -U test -f terasoluna-tourreservation-selenium/pom.xml
